version: '2'
services:
  cache:
    image: redis:5.0.0-alpine
    hostname: redis
    ports:
      - "6379:6379"
  w2w:
      build:
        context: .
        args:
          - W2W_VERSION=0.0.1
      hostname: w2w-app
      environment:
        - W2W_TITLES_PAGES_PER_REQUEST=10
        - W2W_THREAD_POOL_SIZE=32
        - REDIS_HOST=redis
        - W2W_LOGGING_LEVEL=INFO
        - W2W_HTTP_CLIENT_DEFAULT_DELAY_MILLIS=99
        - W2W_HTTP_CLIENT_DELAY_BY_DOMAIN_MILLIS={'"metacritic.com"':500,'"filmweb.pl"':101}
        - JVM_OPTS=-Xmx2G
          -Xms2G
          -XX:+TieredCompilation
          -XX:InitialCodeCacheSize=256m
          -XX:ReservedCodeCacheSize=256m
          -XX:-UseBiasedLocking
          -XX:+PreserveFramePointer
          -XX:+UnlockExperimentalVMOptions
          -XX:+UseZGC
          -XX:+UseNUMA
          -XX:+UseStringDeduplication
          -Xlog:gc:stdout:time
      ports:
        - "8080:8080"
        - "9999:9999"
      links:
        - "cache:redis"
