cache:
  image: redis:4.0.0-alpine
  hostname: redis
  ports:
    - "6379:6379"
w2w:
    build: ./what-to-watch-boot
    hostname: w2w-app
    environment:
      - W2W_TITLES_CRAWLED_PAGES_LIMIT=20
      - W2W_THREAD_POOL_SIZE=32
      - REDIS_HOST=redis
      - W2W_LOGGING_LEVEL=INFO
    ports:
      - "8080:8080"
      - "9999:9999"
    links:
      - "cache:redis"
