cache:
  image: redis:3.0.3
  hostname: redis
  ports:
    - "6379:6379"
w2w:
    build: ./what-to-watch-boot
    hostname: w2w-app
    environment:
      - W2W_TITLES_CRAWLED_PAGES_LIMIT=25
    links:
      - "cache:redis"
